// <auto-generated />
using System;
using EF_Core_Inheritance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Core_Inheritance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250827155636_addTablePerType")]
    partial class addTablePerType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Core_Inheritance.TablePerHierarchy.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("EmployeeType").HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerType.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerHierarchy.Models.Contractor", b =>
                {
                    b.HasBaseType("EF_Core_Inheritance.TablePerHierarchy.Models.Employee");

                    b.Property<string>("ContractCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Contractor");
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerHierarchy.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("EF_Core_Inheritance.TablePerHierarchy.Models.Employee");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VacationDays")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("FullTime");
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerHierarchy.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("EF_Core_Inheritance.TablePerHierarchy.Models.Employee");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PartTime");
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerType.Models.Student", b =>
                {
                    b.HasBaseType("EF_Core_Inheritance.TablePerType.Models.Person");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerType.Models.Teacher", b =>
                {
                    b.HasBaseType("EF_Core_Inheritance.TablePerType.Models.Person");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerType.Models.Student", b =>
                {
                    b.HasOne("EF_Core_Inheritance.TablePerType.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("EF_Core_Inheritance.TablePerType.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF_Core_Inheritance.TablePerType.Models.Teacher", b =>
                {
                    b.HasOne("EF_Core_Inheritance.TablePerType.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("EF_Core_Inheritance.TablePerType.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
